"""Independent oracles for the P0-02 bytes and the P0-03 digests.

The committed vectors were generated by ``core.canonical`` and ``hashlib``.
Comparing them back to those same components proves only that nothing has changed
since -- it is a regression check, not a correctness check. If the encoder had been
wrong on the first day, the vectors would have enshrined the wrong bytes and every
suite would still be green.

This module breaks that circularity with three oracles that do not depend on the
implementation under test:

1. **CPython's own ``json`` encoder.** For the restricted AURA-CANON/1 domain
   ``json.dumps(sort_keys=True, separators=(",", ":"), ensure_ascii=False)`` produces
   the same bytes -- except where the contract's UTF-16 member ordering diverges from
   code-point order, which is asserted explicitly rather than excused.
2. **A second implementation written from the contract text**
   (``conformance/_contract_oracle.py``), using different mechanisms, covering the
   astral case that oracle 1 cannot.
3. **An external SHA-256 binary** (``sha256sum`` or ``openssl``), which removes
   ``hashlib`` from the trust base for the recorded digests.

None of these is a third-party conformance suite for AURA-CANON/1; no such suite
exists, because the form is defined in this repository. What they establish is that
the recorded bytes and digests are not merely whatever this implementation happened
to emit.
"""

import json
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

from _m0 import build_entry, load_vectors, vectors_by_name

from conformance._contract_oracle import (OracleRejection,
                                          canonicalise_from_contract,
                                          utf16_code_units)

# The one vector whose bytes CPython's json encoder cannot reproduce, because the
# contract's ordering rule is exactly what differs. Named, not silently skipped.
UTF16_ORDERING_VECTOR = "unicode-astral"


def _stdlib_json_oracle(obj) -> bytes:
    return json.dumps(
        obj, sort_keys=True, separators=(",", ":"), ensure_ascii=False
    ).encode("utf-8")


class StdlibJsonOracleTest(unittest.TestCase):
    """Oracle 1: CPython's json encoder, which nobody here wrote."""

    def test_every_vector_except_the_ordering_case_matches_stdlib_json(self):
        checked = 0
        for vector in load_vectors():
            if vector["name"] == UTF16_ORDERING_VECTOR:
                continue
            with self.subTest(vector=vector["name"]):
                committed = bytes.fromhex(vector["canonical_hex"])
                representation = build_entry(vector["input"]).canonical_representation()
                self.assertEqual(
                    committed, _stdlib_json_oracle(representation),
                    f"{vector['name']}: committed bytes disagree with CPython's "
                    f"own json encoder",
                )
                checked += 1
        self.assertEqual(len(load_vectors()) - 1, checked)

    def test_the_ordering_vector_differs_from_stdlib_json_in_order_alone(self):
        """The divergence must be the documented rule, not an encoding bug.

        Same member set, same values, different order: CPython sorts member names by
        code point, the contract sorts by UTF-16 code unit. If this vector ever
        matched stdlib json, the UTF-16 rule would have stopped being implemented.
        """
        vector = vectors_by_name()[UTF16_ORDERING_VECTOR]
        committed = bytes.fromhex(vector["canonical_hex"])
        representation = build_entry(vector["input"]).canonical_representation()
        stdlib = _stdlib_json_oracle(representation)

        self.assertNotEqual(committed, stdlib, "the UTF-16 ordering rule is not in effect")
        self.assertEqual(json.loads(committed.decode("utf-8")),
                         json.loads(stdlib.decode("utf-8")),
                         "the two encodings must differ only in member order")

        names = list(json.loads(committed.decode("utf-8"))["metadata"])
        self.assertEqual(sorted(names, key=utf16_code_units), names,
                         "committed order must be UTF-16 code-unit order")
        self.assertNotEqual(sorted(names), names,
                            "this vector must distinguish the two orderings")


class ContractOracleTest(unittest.TestCase):
    """Oracle 2: a second implementation written from the contract, not the code."""

    def test_every_vector_matches_the_contract_derived_implementation(self):
        for vector in load_vectors():
            with self.subTest(vector=vector["name"]):
                representation = build_entry(vector["input"]).canonical_representation()
                self.assertEqual(
                    bytes.fromhex(vector["canonical_hex"]),
                    canonicalise_from_contract(representation).encode("utf-8"),
                    f"{vector['name']}: core.canonical and an implementation written "
                    f"from the contract text disagree; one of them is wrong",
                )

    def test_the_two_implementations_agree_on_the_reference_package(self):
        """Beyond the vectors: the shipped evidence must survive the same check."""
        from _m0 import REFERENCE_PACKAGE

        text = (REFERENCE_PACKAGE / "evidence/audit.jsonl").read_text(encoding="utf-8")
        records = [json.loads(line) for line in text.splitlines() if line.strip()]
        self.assertTrue(records)
        for index, record in enumerate(records):
            with self.subTest(record=index):
                from core.canonical import canonical_bytes

                protected = {k: v for k, v in record.items() if k != "entry_hash"}
                self.assertEqual(
                    canonical_bytes(protected),
                    canonicalise_from_contract(protected).encode("utf-8"),
                )

    def test_the_oracle_imports_nothing_from_the_implementation(self):
        """Guard against the oracle being quietly reduced to a call into the code.

        Checked on the parsed import statements, not on a text search: prose in the
        module's own docstring names ``core.canonical`` in order to explain what the
        oracle is independent of.
        """
        import ast

        source = (Path(__file__).resolve().parent / "_contract_oracle.py").read_text(
            encoding="utf-8"
        )
        imported: list[str] = []
        for node in ast.walk(ast.parse(source)):
            if isinstance(node, ast.Import):
                imported += [alias.name for alias in node.names]
            elif isinstance(node, ast.ImportFrom) and node.module:
                imported.append(node.module)

        offenders = [name for name in imported
                     if name.split(".")[0] in ("core", "app", "json")]
        self.assertEqual(
            [], offenders,
            f"the oracle must not delegate to the implementation or to a JSON "
            f"encoder; it imports {offenders}",
        )

    def test_the_oracle_derives_utf16_units_correctly(self):
        """Anchor the oracle's own mechanism against known values."""
        self.assertEqual((0x007A,), utf16_code_units("z"))
        self.assertEqual((0xFFFD,), utf16_code_units("�"))
        # U+1F510: 0x1F510 - 0x10000 = 0xF510 -> lead D83D, trail DD10.
        self.assertEqual((0xD83D, 0xDD10), utf16_code_units("\U0001F510"))
        self.assertLess((0xD83D, 0xDD10), (0xFFFD,),
                        "astral must sort below U+FFFD under UTF-16 ordering")

    def test_the_oracle_rejects_what_the_contract_excludes(self):
        for value in ({"a": None}, {"a": 1.5}, {"a": "\ud800"}, {"\udfff": "a"}):
            with self.subTest(value=repr(value)):
                with self.assertRaises(OracleRejection):
                    canonicalise_from_contract(value)


def _external_sha256(data: bytes) -> str | None:
    """Digest ``data`` with an external binary, or None if none is available."""
    with tempfile.NamedTemporaryFile() as handle:
        handle.write(data)
        handle.flush()
        if shutil.which("sha256sum"):
            out = subprocess.run(["sha256sum", handle.name], capture_output=True,
                                 text=True, check=True).stdout
            return out.split()[0]
        if shutil.which("openssl"):
            out = subprocess.run(["openssl", "dgst", "-sha256", handle.name],
                                 capture_output=True, text=True, check=True).stdout
            return out.strip().rsplit(" ", 1)[-1]
    return None


class ExternalDigestOracleTest(unittest.TestCase):
    """Oracle 3: an external SHA-256, so hashlib is not both author and judge."""

    def test_an_external_sha256_implementation_is_available(self):
        """This oracle must actually run. A silently skipped oracle is not evidence."""
        self.assertTrue(
            shutil.which("sha256sum") or shutil.which("openssl"),
            "no external SHA-256 binary found; the P0-03 digests would then rest on "
            "hashlib alone and this oracle would prove nothing",
        )

    def test_every_recorded_digest_is_confirmed_externally(self):
        for vector in load_vectors():
            with self.subTest(vector=vector["name"]):
                external = _external_sha256(bytes.fromhex(vector["canonical_hex"]))
                self.assertIsNotNone(external)
                self.assertEqual(
                    vector["sha256"], external,
                    f"{vector['name']}: recorded digest disagrees with an external "
                    f"SHA-256 implementation",
                )


class WorkedExampleTest(unittest.TestCase):
    """The contract's worked example must be exactly reproducible.

    Contract section 3.1 spells out one vector end to end so an independent engineer
    can derive the bytes and the digest from prose alone. If the document and the
    vector ever drift apart, the document stops being a specification.
    """

    CONTRACT = (Path(__file__).resolve().parents[2]
                / "docs/contract/M0-EVIDENCE-CONTRACT.md")

    def test_the_documented_bytes_match_the_committed_vector(self):
        contract = self.CONTRACT.read_text(encoding="utf-8")
        vector = vectors_by_name()["minimal"]

        self.assertIn(vector["canonical_utf8"], contract,
                      "the worked example's canonical bytes are not in the contract")
        self.assertIn(vector["sha256"], contract,
                      "the worked example's SHA-256 is not in the contract")
        self.assertIn(f"{vector['canonical_length']} bytes", contract)

    def test_the_worked_example_is_reproducible_from_the_contract_alone(self):
        """Derive it with the contract-written oracle and an external digest."""
        vector = vectors_by_name()["minimal"]
        representation = build_entry(vector["input"]).canonical_representation()

        produced = canonicalise_from_contract(representation).encode("utf-8")
        self.assertEqual(vector["canonical_utf8"].encode("utf-8"), produced)
        self.assertEqual(vector["canonical_length"], len(produced))
        self.assertEqual(vector["sha256"], _external_sha256(produced))


if __name__ == "__main__":
    unittest.main()
