#!/usr/bin/env python3
"""Regenerate the M0 conformance vectors and the reference evidence package.

The vectors this writes are **known-answer tests generated by this implementation**.
They lock the canonical form against silent regression: any change to the encoder,
the field set, the ordering, or the confidence scale changes the recorded bytes and
fails the suite. They are not independent third-party vectors, and
docs/contract/M0-EVIDENCE-CONTRACT.md section 8 says so plainly. The bytes are
recorded in full precisely so that a human, or a second implementation, can review
them rather than trust a digest.

Standard library only (ADR-0002/ADR-0004).

Usage:
    python3 tools/build_m0_fixtures.py [--check]

``--check`` regenerates in memory and reports whether the committed files differ,
without writing. CI uses it to prove the fixtures match the implementation.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from app.producer import DecisionEvent, build_package as produce_package  # noqa: E402
from core import M0_AUDIT_SCHEMA  # noqa: E402
from core.chain import entry_preimage  # noqa: E402
from core.models import GENESIS_PREV_HASH, AuditEntry, Violation  # noqa: E402

VECTORS_PATH = REPO_ROOT / "conformance/vectors/m0-canonical-vectors.json"
PACKAGE_ROOT = REPO_ROOT / "evidence/examples/aura-evidence-loan-001"
PACKAGE_ID = "aura-evidence-loan-001"

H_A = "a" * 64
H_B = "b" * 64
H_C = "c" * 64


def _entry(**overrides) -> dict:
    """A representative entry, as the JSON-describable input a vector records."""
    base = {
        "seq": 0,
        "request_id": "req-0001",
        "timestamp": "2026-08-27T10:00:00Z",
        "decision": "DENY",
        "policy_hash": H_A,
        "policy_repr": "loan.underwriting/2",
        "input_hash": H_B,
        "prev_hash": GENESIS_PREV_HASH,
        "violations": [],
        "metadata": {},
        "shadow_hash": None,
        "schema": M0_AUDIT_SCHEMA,
    }
    base.update(overrides)
    return base


def _violation(rule: str, action: str, confidence: str) -> dict:
    # Confidence is recorded as a decimal *string* so the fixture states an exact
    # value rather than one mediated by JSON float parsing.
    return {"rule": rule, "action": action, "confidence": confidence}


def build_entry(spec: dict) -> AuditEntry:
    """Reconstruct an AuditEntry from a vector's recorded input."""
    return AuditEntry(
        seq=spec["seq"],
        request_id=spec["request_id"],
        timestamp=spec["timestamp"],
        decision=spec["decision"],
        policy_hash=spec["policy_hash"],
        policy_repr=spec["policy_repr"],
        input_hash=spec["input_hash"],
        prev_hash=spec["prev_hash"],
        violations=[
            Violation.build(v["rule"], v["action"], v["confidence"])
            for v in spec["violations"]
        ],
        metadata=dict(spec["metadata"]),
        shadow_hash=spec["shadow_hash"],
        schema=spec["schema"],
    )


# Each vector states what property it exists to pin down. A vector whose purpose is
# not stated cannot be reviewed, only re-run.
VECTOR_SPECS: list[tuple[str, str, dict]] = [
    ("minimal", "Smallest well-formed entry: no violations, no metadata, no shadow hash.",
     _entry()),
    ("complete", "Representative entry with every optional member populated.",
     _entry(seq=7, request_id="req-0007", prev_hash=H_C, shadow_hash=H_C,
            decision="REQUIRE_APPROVAL",
            violations=[_violation("LOAN.DTI_EXCEEDED", "BLOCK", "0.95"),
                        _violation("LOAN.MANUAL_REVIEW", "FLAG", "0.5")],
            metadata={"actor": "agent-17", "channel": "batch", "region": "eu-west-1"})),
    ("unicode-bmp", "Non-ASCII BMP text is emitted literally, carried by UTF-8.",
     _entry(policy_repr="policy \u00e9\u00e8\u00fc \u4e2d\u6587 \u0416",
            metadata={"note": "na\u00efve r\u00e9sum\u00e9"})),
    ("unicode-astral", "Astral characters, including in member names, exercise the "
                       "UTF-16 code-unit ordering required by RFC 8785.",
     _entry(policy_repr="emoji \U0001F510\U0001F9FE",
            metadata={"\U0001F510key": "astral name", "\uFFFDkey": "replacement name",
                      "zkey": "ascii name"})),
    ("quotes", "Double quotes escape to \\\" and nothing else.",
     _entry(policy_repr='he said "deny" loudly',
            metadata={'quoted"key': 'quoted"value'})),
    ("backslashes", "Backslashes escape to \\\; a trailing backslash cannot run into "
                    "the closing quote.",
     _entry(policy_repr="C:\\policies\\loan\\", metadata={"path": "a\\\\b"})),
    ("control-characters", "CR, LF, and tab take their short escapes; other C0 "
                           "controls take \\u00xx.",
     _entry(policy_repr="line1\r\nline2\tend\x00\x1f",
            metadata={"raw": "\x08\x0c\x0b"})),
    ("pipes", "Pipe characters are ordinary content and are never delimiters.",
     _entry(policy_repr="a|b||c|", metadata={"k|1": "v|1", "k": "|"})),
    ("literal-text-None", 'The literal text "None" is content, not an absent value.',
     _entry(policy_repr="None", metadata={"opt": "None"})),
    ("literal-text-Some-empty", 'The literal text Some("") is content, not an empty value.',
     _entry(policy_repr='Some("")', metadata={"opt": 'Some("")'})),
    ("optional-absent", "An absent shadow hash contributes no member at all. Pairs "
                        "with optional-present, from which it differs in that member alone.",
     _entry(request_id="req-optional", shadow_hash=None)),
    ("optional-present", "A present shadow hash contributes a member; compare with "
                         "optional-absent.",
     _entry(request_id="req-optional", shadow_hash=H_C)),
    ("metadata-key-absent", "Absent metadata key. Compare with metadata-key-empty: this "
                            "is the None / Some(\"\") distinction.",
     _entry(request_id="req-metadata", metadata={"present": "x"})),
    ("metadata-key-empty", "Metadata key present with an empty value. Must not "
                           "canonicalise to the same bytes as metadata-key-absent.",
     _entry(request_id="req-metadata", metadata={"present": "x", "opt": ""})),
    ("violations-empty", "An empty violation array is a member, not an absence.",
     _entry(request_id="req-violations", violations=[])),
    ("violations-ordered-ab", "Two violations in producer order A, B.",
     _entry(request_id="req-violations",
            violations=[_violation("RULE.A", "BLOCK", "0.25"),
                        _violation("RULE.B", "FLAG", "0.75")])),
    ("violations-ordered-ba", "The same two violations in order B, A. Ordering is "
                              "protected, so these bytes must differ from "
                              "violations-ordered-ab.",
     _entry(request_id="req-violations",
            violations=[_violation("RULE.B", "FLAG", "0.75"),
                        _violation("RULE.A", "BLOCK", "0.25")])),
    ("confidence-boundaries", "The four required confidence conversions: "
                              "0.0->0, 0.5->5000, 0.95->9500, 1.0->10000.",
     _entry(violations=[_violation("C.ZERO", "LOG", "0.0"),
                        _violation("C.HALF", "LOG", "0.5"),
                        _violation("C.NINETYFIVE", "LOG", "0.95"),
                        _violation("C.ONE", "LOG", "1.0")])),
    ("decision-allow", "Decision participates in the preimage; compare with minimal.",
     _entry(decision="ALLOW")),
    ("injection-shaped-content", "Content shaped like canonical syntax is escaped as "
                                 "data and cannot restructure the preimage.",
     _entry(policy_repr='","entry_hash":"deadbeef',
            metadata={"x": '"}],"seq":99,"z":"'})),
]


def build_vectors() -> dict:
    vectors = []
    for name, purpose, spec in VECTOR_SPECS:
        entry = build_entry(spec)
        preimage = entry_preimage(entry)
        vectors.append({
            "name": name,
            "purpose": purpose,
            "input": spec,
            "canonical_utf8": preimage.decode("utf-8"),
            "canonical_hex": preimage.hex(),
            "canonical_length": len(preimage),
            "sha256": hashlib.sha256(preimage).hexdigest(),
        })
    return {
        "vector_set": "M0 canonical evidence vectors (P0-02 bytes, P0-03 digests)",
        "canonical_form": "AURA-CANON/1",
        "digest": "SHA-256",
        "audit_schema": M0_AUDIT_SCHEMA,
        "generated_by": "tools/build_m0_fixtures.py",
        "authority": (
            "Defined by ADR-0005 in this repository. NOT recovered from, and NOT "
            "claimed compatible with, any prior Aura implementation."
        ),
        "vectors": vectors,
    }


# The reference scenario, stated once. `tests/_product.py` imports these, so the
# product-loop suites exercise the producer against the same events the committed
# reference package is built from, rather than a second, slightly different loan
# scenario that would quietly diverge from it.
LOAN_POLICY = {
    "policy_id": "loan.underwriting",
    "version": 2,
    "rules": [
        {"id": "LOAN.DTI_EXCEEDED", "action": "BLOCK", "threshold_bp": 4300},
        {"id": "LOAN.MANUAL_REVIEW", "action": "FLAG", "threshold_bp": 5000},
    ],
}

# The loan scenario as application input: what a decision engine would hand the
# producer. Everything protected -- sequence numbers, chain links, digests, the
# manifest terminus -- is computed from these by `app.producer`, not stated here.
LOAN_EVENTS = [
    DecisionEvent(
        request_id="loan-001-intake", timestamp="2026-08-27T09:15:00Z",
        decision="ALLOW", input_hash=H_B, policy_repr="loan.underwriting/2",
        metadata={"actor": "agent-17", "stage": "intake"},
    ),
    DecisionEvent(
        request_id="loan-001-assess", timestamp="2026-08-27T09:15:04Z",
        decision="REQUIRE_APPROVAL", input_hash=H_C,
        policy_repr="loan.underwriting/2", shadow_hash=H_A,
        violations=[_violation("LOAN.DTI_EXCEEDED", "BLOCK", "0.95"),
                    _violation("LOAN.MANUAL_REVIEW", "FLAG", "0.5")],
        # Deliberately awkward text: a pipe, escaped quotes, and a backslash, so the
        # reference package exercises canonical escaping rather than only plain ASCII.
        metadata={"actor": "agent-17", "stage": "assess",
                  "note": 'ratio 0.47 | flagged "high" \\ review'},
    ),
    DecisionEvent(
        request_id="loan-001-settle", timestamp="2026-08-27T09:16:31Z",
        decision="DENY", input_hash=H_A, policy_repr="loan.underwriting/2",
        violations=[_violation("LOAN.DTI_EXCEEDED", "BLOCK", "1.0")],
        # An empty metadata value is a present member, not an absent one.
        metadata={"actor": "reviewer-3", "stage": "settle", "note": ""},
    ),
]


def build_package() -> dict[str, bytes]:
    """Build the reference evidence package as a path -> bytes mapping.

    The package is produced by ``app.producer`` -- the same code path an application
    uses through ``aura record`` -- rather than by a construction private to this
    generator. That is the point: a reference package assembled by a second,
    fixture-only implementation would prove that the fixtures agree with themselves,
    not that the product produces conformant evidence.
    """
    policy, events = LOAN_POLICY, LOAN_EVENTS

    files = dict(produce_package(PACKAGE_ID, policy, events))

    # expected/result.json is NON-NORMATIVE fixture metadata (contract section 6.2):
    # the verifier never reads it, and the manifest does not bind it. It is added
    # here, by the fixture generator, and deliberately not by the producer -- a
    # package an application produces should carry evidence, not an assertion about
    # the verdict it expects to receive.
    entry_count = json.loads(files["manifest.json"])["entry_count"]
    files["expected/result.json"] = (json.dumps({
        "status": "VERIFIED",
        "package_id": PACKAGE_ID,
        "entries": entry_count,
        "reasons": [],
    }, sort_keys=True, indent=2) + "\n").encode("utf-8")

    return files


def _write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="report drift without writing")
    args = parser.parse_args(argv)

    outputs: dict[Path, bytes] = {
        VECTORS_PATH: (json.dumps(build_vectors(), indent=2, ensure_ascii=False,
                                  sort_keys=False) + "\n").encode("utf-8"),
    }
    for relative, data in build_package().items():
        outputs[PACKAGE_ROOT / relative] = data

    if args.check:
        drifted = [
            str(path.relative_to(REPO_ROOT))
            for path, data in outputs.items()
            if not path.is_file() or path.read_bytes() != data
        ]
        if drifted:
            print("committed fixtures differ from the implementation:", file=sys.stderr)
            for name in sorted(drifted):
                print(f"  - {name}", file=sys.stderr)
            return 1
        print(f"m0 fixtures: OK -- {len(outputs)} file(s) match the implementation")
        return 0

    for path, data in outputs.items():
        _write(path, data)
    print(f"m0 fixtures: wrote {len(outputs)} file(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
